### ISSUE TITLE
Location of fixes 

### ISSUE THREAD

**Issue by franceme** [ballerina-platform/plugin-vscode-compiler-toolkit#23]
Closing this since the issue is moved to the ballerina vs code extension repository.

_Originally posted by @KavinduZoysa in https://github.com/ballerina-platform/plugin-vscode-compiler-toolkit/issues/17#issuecomment-2377799427_

Can you please link the location where this fix was applied?

**Comment by anupama-pathirage** [comment]
@franceme This issue is moved to https://github.com/wso2/ballerina-vscode/issues/582
