### ISSUE TITLE
Add Syntax API Code Gen related functionality into the extension

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/plugin-vscode-compiler-toolkit#3]
**Description:**
$subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/29819

**Comment by SumayyaZiyad** [comment]
@kdsuneraavinash we can close this right?

**Comment by kdsuneraavinash** [comment]
Fixed by #4
